Greeting Message
ShahierNashaat/hello-rails-react pull request #1
Opened 2022-03-21 19:07 UTC by ShahierNashaat

### Pull request for review create rails-react app using Ruby on Rails, React, and Redux 

- Create a new Rails app called 'hello-rails-react'.
 - Initialize your project with Git.
 - Set up your project with `webpacker` the `react-rails` gems as describe in the previous lesson's tutorial.
 - Make sure that your project has a Postgres database set up. 
 - Create a table for storing your messages and create 5 different greetings. 
 - Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
 - Create a static view that will be the root of your app.

---------

- Create the `App` component with react-router and render it in your static view.
- Create the `Greeting` component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.

2022-03-21 21:13 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

### Hello @ShahierNashaat  ✋🏼 
#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___
- You have one commit for everything. For best practices, you should commit often. [Git Commit Best Practices](https://www.perforce.com/blog/vcs/git-best-practices-git-commit)

![almost](https://media.giphy.com/media/oHwvp6bEuiog0bxg2P/giphy.gif)

___

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_


_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mentioning me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._
___
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-03-21 21:13 UTC, ahmetbozaci commented on app/javascript/components/Greeting.js
> +import { fetchmessage } from '../redux/message/api';
- [ ] `fetchmessage` Path is wrong that's why it is giving an error. Please fix it.
![image](https://user-images.githubusercontent.com/38635158/159363250-8aa43153-a6c5-4366-938f-622ffe1ae2ac.png)

2022-03-21 21:13 UTC, ahmetbozaci commented on app/javascript/components/Greeting.js
> +  }, []);
- [ ] You should fix this error.

![image](https://user-images.githubusercontent.com/38635158/159363394-13efccbd-8daf-4570-a7b1-4f83606f6124.png)

2022-03-21 21:13 UTC, ahmetbozaci commented on config/routes.rb
> +  root 'static#index'
- [ ] Something is wrong in your route or `fetchmessage` function in `redux/reducers/messages` file. Please fix it.

![image](https://user-images.githubusercontent.com/38635158/159363904-c241c09d-465d-4c39-9cbb-7ac9d231790f.png)

2022-03-21 21:13 UTC, ahmetbozaci commented on config/database.yml
> +  port: 5432
### OPTIONAL
- [ ] It is always good practice not to expose your database login information. Consider using the env file for all sensitive information about your application.

2022-03-22 08:37 UTC, dasileker approved these changes
### **Hi @ShahierNashaat,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 08:44 UTC, merged